# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6b9e2a7c98e68418ac8f3effc79113b2"
name = "Upsell Cross Sell Booster - St"
application_url = "https://localhost:3000"
embedded = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  # GDPR webhooks (customers/data_request, customers/redact, shop/redact)
  # are mandatory and automatically registered by Shopify.
  # DO NOT declare them here - only the handler endpoints are needed.

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_products,unauthenticated_write_checkouts"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ ]

[build]
automatically_update_urls_on_dev = true
